"""added name column

Revision ID: 403515de8958
Revises: 6e1db5433cbb
Create Date: 2018-03-21 14:42:40.546605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '403515de8958'
down_revision = '6e1db5433cbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'name')
    # ### end Alembic commands ###
