"""added UserLikedMessages table

Revision ID: edca7f8a2d50
Revises: 403515de8958
Create Date: 2018-03-22 14:50:43.203984

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edca7f8a2d50'
down_revision = '403515de8958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('likes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('liked_id', sa.Integer(), nullable=True),
    sa.Column('likes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['liked_id'], ['users.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['likes_id'], ['messages.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('likes')
    # ### end Alembic commands ###
